### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by peterennisrda** [fssrepository/fms-design#2]
The project is interesting, but is this really the correct license?

"The project has limited copyleft approach, which means, any stuff related to this project needs to be shared. (commonly used algorithm / data structures / improvements / bug fixes etc.) You are free to use this project in any project of yours without sharing your private project code. (the GNU GPL v3 licence has been introduced only to have enough contributors, not to steal any idea which based on the mapping solution - you don't need to share private code which is related only for example pizza ordering, social sites etc., but you are required to separate the mapping logic, and push back your mapping improvements, which is related to the software, not for the service, as every component in this map should work offline also)"

If you are making components (libraries/modules) then LGPL3 may be better.

It is a lawyer fight to separate use with a corporate product and they
will not allow GPL, but many will allow LGPL.

You get potentially broader support with less problems.

I have looked at other mapping solutions and have to reject GPL3 due to corporate policy.

**Comment by raxim1** [comment]
The main problem is, nobody really interested in my approach, you are right, but it was not available at github. I need some sort of mapping solution anyway, i have shared the idea, but if nobody invest time on this, just me, than it will be closed source and included in my project only (i have invested 2-3 monthes full time to figure out something trying out all the OSM mapping software outdated zoo). To my project i need some basic stuff later on, which are more flexible to use than google map. I will change the licence.

I just want to avoid that i will be exploited, as it's a very challenging and big stuff. Nobody can afford alone to work on a project for a year freely full time.

**Comment by peterennisrda** [comment]
Thanks for the detailed answer.

My requirement is a map interface for government agencies that do not want licensing issues with
Google/Bing/Esri etc.
They may also require some data to be private behind their own firewall.
Geo data must be stored in a standard format so there is no lock-in.
A mobile app interface is needed.

I have been using Ionic and will be moving towards the PWA model with
optional apps for Apple/Google store.

Do you have a starter sample? What is the best way to look further into this?

**Comment by raxim1** [comment]
At the moment the fms repository contains some basic code in javascript (which is using some webworker part), but if you look at the end of the design document, it contains a proof of concept. I think the javascript pbf file converter itself is a dead end as it needs to overrule many browser limits, but the java version very likely some days or a week work for a good developer.

If you need only to show some clickable icon only on the screen, like my project, my gut feeling this project might be very helpful to start, but if you need routing and many fancy stuff, Google built it for years.
I'm not saying it's not reproducible, but takes time, and this project is not aiming to replace the Google map as a whole, just the basic functionality what everybody would like in their project.

There is a basic java project called pbfreader, which can just load a file in a very fast way.
I think that project is a good start for the file converter. (in javascript there is a pbf reader part already, how you can read a pbf file)

I detailed the related issues here, pls. try to read it through thinking on java implementation instead.
https://github.com/fssrepository/fms/issues

At the moment i'm more worried on my other project, which has been simplified a lot, and can live without map, if i hit the google limit.

When the file converter has been finished, than the reader and rendering part using svg might be not that big deal.

To be honest i just shared my code when i felt, that i haven't more time on it, so it might not be the best code, what i have done, but it's some sort of sample, and a good summary of my work.

The big deal i think that i made the design document, and touched all the components which is needed to create some sort of map.

In the first part also does not need p2p and so, so it would be really helpful, if you could do something on that file converter area following my design. I don't think it needs too much time. (1-2 weeks can prove some things) After that you need to read from the file and render to an svg and that's all, which can be written in javascript. (you need to add a zoom interface to it, and move) - there is a facs repository what i'm working on right now, i have already some experience, you don't need hammer, you can very easily write this logic looking at https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events/Pinch_zoom_gestures

Pls. don't use pointer event, as google screwed up, and broken the functionality as i have experienced.
(you can make a reusable code calling from mousedown/mousemove and touchstart/touchmove)

At first the code might be hard to read as it's unfinished, but i will jump back, when i finish the other project, very likely needs 2-3 month to do so.

**Comment by peterennisrda** [comment]
Please clarify this part as the language is confusing:

"My experience is that investing time on this project to make a clickable map with google style, is not harder to go to the switch2osm route, which has got a tremendous maintenance cost in the future, and very hard to configure also. I've never done this repository if i wasn't horrified the alternative non-limited options next to the Google."

**Comment by raxim1** [comment]
The main reasons, why i started this project is the following:

1, I wanted to make a hybrid app, not to code three times.
2, I have tried to use some cordova plugin, but at the end they were so buggy, that you cannot rely on those. (so i didn't even dare to try the google map cordova plugin)
3, I have tried all the osm related software, and i saw basic programming errors in java part also.
4, you can style the open street map similar to google (i think it's similar than to compare gimp with photoshop - gimp is hard to use, but you can do anything with it)
5, To configure an osm map following the switch2osm site is not easy. Looking at the carto css files, which is 8 years old format, the configuration is very scattered, it's not just one big file, there are shape files, dbx files and so on. You need to upload everything to a postgre sql db. (mysql does not support some features that much, so it might cause trouble, what you need to fix)
6, At the end you end up with a 1-2 TB tiles, so it requires a good server. (If you have some thousands customer per day, it might need really some steel) - that kind of server needs 32-64GB ram. The maintenance might not be that easy as just do it once.
7, Even if OSM is free to use, most of the software are outdated totally, and you are ending up just with pure bug fixing.
8, When you are done with tiles generation, you might need to generate it again as they are static.
9, MapBox has got some up-to-date software library, which is also not easy to understand, but reliable, though it's tight coupled to their infrastructure, as it's very hard also to recreate similar.
10, MapBox is using Vector tiles, which can be dynamically changed.

My design idea is not just solving maintenance issues. It's going to reduce the size even the 37GB pbf, so it will be the DB, what you can read efficiently. If my idea is reaching the 8GB target for the whole world, than you can store part of the map, what the user interested in on mobile device instead of a server and just attach your service to it as an additional layer (so the static data would be downloaded only once even into a browser). I would say it is easier than the MapBox vector tiles, but it's not tight coupled to anything.


11, Clickable means, that you can put some dots to the map, or shapes, what you can click on.
Routing takes more time, and never will be google one as, you need live traffic information to do so.

Everything is in the doc, you just need to judge whether it's enough for you or not. To clarify the whole, at the moment i'm just thinking on the very basic one, show some drop on the screen, click on them, and show some info window. (that's what i see is achievable in the near future)

If it would have a serious team behind the whole repo, than it wouldn't be the question, how much functionality can be done, which is properly written, but to my case, i just would like to avoid the 25.000 daily limit javascript hit. If i need to develop for ios and android separately, than i would personally invest on this project. Until i'm not hitting the google map javascript limit, personally i'm fine with the google solution for a while. (premium licence needed only later on)

The real benefit, that when somebody is looking for your site, it tends to search locally, so a person who lives in India very likely wouldn't like to download an US map.

The interface is containing clickable squares. if you click on them, it's automatically trying to download the part of the map file on different zoom level.

Either way, what you can read from my design it's a very mature work. Taken month to collect that amount of info. (contains the best links also, what you can get by looking infos)

If you are interested pls. familiarize yourself with the concepts, i have only limited time to support anybody on this matter.
